# DEEP LEARNING 

## TUẦN 2: NUMPY - PANDAS - MATPLOTLIB

### NUMPY

In [1]:
# numpy là thư viện kiểu list 
# vì : chạy nhanh, có nhiều hàm tích hợp dễ sử dụng cho AI
import numpy as np

In [4]:
# thử tạo list
pl = [1,2,3,4,5]
print(pl)

# chuyển sang numpy array
na = np.array(pl)
print(type(na))

[1, 2, 3, 4, 5]
<class 'numpy.ndarray'>


In [5]:
# list trong python có thể hỗ trợ nhiều kiểu dữ liệu khác nhau
list_2 = [1, 2.5, 'hello', True]

In [11]:
list_3 = [1, 2, 3, 4, 5.1]
np_list_3 = np.array(list_3)
print(np_list_3)

[1.  2.  3.  4.  5.1]


In [18]:
# chuyển đổi
np_list_int = np_list_3.astype(int)
print(np_list_int)

[1 2 3 4 5]


In [19]:
# accessing và indexing
x = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
# x = np,array(range(1,9))

print(x[3])  # first element

40


In [26]:
# lấy nhiều hơn 1 phần tử
print(x[0:3])  # elements from index 2 to 4
# lấy 3-8 theo 3 cách
print(x[2:8])
print(x[2:-1])
print(x[-1:-1])
print(x[2:6:2])  # elements from index 2 to 7 with step 2

[10 20 30]
[30 40 50 60 70 80]
[30 40 50 60 70 80]
[]
[30 50]


In [28]:
#đặt list các index muốn lấy
x_indices = [1, 3, 5]
print(x[x_indices])  # elements at index 1, 3, and 5

[20 40 60]


In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])
npl = np.array(data)
print(npl)
print(npl[0, 1])  # element at row 1, column 2
#take 3,4,5,6
print(npl[1:, :])  # elements from row 2 to end, all columns
#other way
print(npl[1: , 0:2])  # elements from row 2 to end, 

[[1 2]
 [3 4]
 [5 6]]
2
[[3 4]
 [5 6]]
[[3 4]
 [5 6]]


In [63]:
# lấy số 1,3,5
print(npl[[0,-2,2], 0])  # elements at row 1 and 3, column 1

[1 3 5]


In [66]:
# lấy 1, 5 
print(npl[[0,2], 0])  # elements at row 1 and 3, column 1
# cach khac
print(npl[[0,2], :][:,-2])  # elements at row 1 and 3, column 1

[1 5]
[1 5]


In [68]:
x = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
]

npList = np.array(x)
# lấy 2, 6, 10, 14, 7 , 11
print(npList[:, 1])  # elements at column 2
print(npList[1:3, 2])  # elements at row 2 to

[ 2  6 10 14]
[ 7 11]


In [74]:
# chỉ lấy 4,7,10 chéo
print(npList[[0, 1, 2], [3, 2, 1]])  # elements at (1,4), (2,3), (3,2)
#lay 16 15 13
print(npList[3, :][::-1])  # elements at row 4 in reverse order
# cach khac lay 16 15 14 13
print(npList[-1, ::-1])  # elements at row 4 in reverse

[ 4  7 10]
[16 15 14 13]
[16 15 14 13]


In [78]:
npx = np.arange(10)
print(npx)

print(npx % 2 == 0)

[0 1 2 3 4 5 6 7 8 9]
[ True False  True False  True False  True False  True False]


In [80]:
cond1 = npx % 2 != 0
cond2 = npx < 5
cond3 = npx > 0

print(npx[cond1 & cond2 | cond3])  # odd numbers less than 5
print(npx[cond1 | cond2])  # odd numbers or numbers less than 5

[1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 7 9]


### BTVN KO VUI VE
1. cho ma trận = [[99,99,99,99],[99,99,99,99],[99,99,99,99]] hãy tưởng tượng ô 99 trống, giả sử 1 là x, giả sử 0 là o, lấy đầu vào từ phía x và phía o luân phiên, nếu đầu vào từ phía x là (0,0) thì : ma trận sẽ trở thành: [[x,99,99,99],[99,99,99,99],[99,99,99,99]], nếu đầu vào từ phía o cũng là (0,0) thì thông báo nhập lại, nếu không nhập thì điền vào ma trận,  Nếu người đầu tiên có 3 phần tử liên tiếp thì dừng

In [ ]:
import sys

def in_ma_tran(mt):
    for hang in mt:
        print(hang)
    print("-" * 20)

def kiem_tra_thang(mt, nguoi_choi):
    # Kiểm tra hàng ngang (3 ô liên tiếp)
    for r in range(3):
        for c in range(2): # Cột 0,1 vì chỉ cần kiểm tra bắt đầu từ đó (0,1,2 hoặc 1,2,3)
            if mt[r][c] == nguoi_choi and mt[r][c+1] == nguoi_choi and mt[r][c+2] == nguoi_choi:
                return True
    
    # Kiểm tra hàng dọc (3 ô liên tiếp)
    for r in range(1): # Chỉ có thể bắt đầu từ hàng 0 (0,1,2)
        for c in range(4):
            if mt[r][c] == nguoi_choi and mt[r+1][c] == nguoi_choi and mt[r+2][c] == nguoi_choi:
                return True
                
    # Kiểm tra chéo chính (\)
    for r in range(1):
        for c in range(2):
            if mt[r][c] == nguoi_choi and mt[r+1][c+1] == nguoi_choi and mt[r+2][c+2] == nguoi_choi:
                return True
                
    # Kiểm tra chéo phụ (/)
    for r in range(1):
        for c in range(2, 4):
            if mt[r][c] == nguoi_choi and mt[r+1][c-1] == nguoi_choi and mt[r+2][c-2] == nguoi_choi:
                return True
    return False

# Khởi tạo
ma_tran = [[99, 99, 99, 99] for _ in range(3)]
luot_di = 0 # Chẵn là x, Lẻ là o
ket_thuc = False

print("Bắt đầu trò chơi (Nhập tọa độ dạng: hang cot). Ví dụ: 0 0")
in_ma_tran(ma_tran)

# Giả lập vòng lặp game (Lưu ý: Bạn cần chạy code này để nhập liệu)
while not ket_thuc:
    nguoi_choi = 'x' if luot_di % 2 == 0 else 'o'
    try:
        nhap = input(f"Lượt của {nguoi_choi}, nhập tọa độ (hàng cột): ")
        r, c = map(int, nhap.split())
        
        # Kiểm tra tọa độ hợp lệ
        if 0 <= r < 3 and 0 <= c < 4:
            if ma_tran[r][c] == 99:
                ma_tran[r][c] = nguoi_choi
                in_ma_tran(ma_tran)
                
                if kiem_tra_thang(ma_tran, nguoi_choi):
                    print(f"Người chơi {nguoi_choi} đã chiến thắng với 3 ô liên tiếp!")
                    ket_thuc = True
                
                luot_di += 1
            else:
                print("Ô này đã được điền, vui lòng nhập lại!")
        else:
            print("Tọa độ ngoài phạm vi (hàng 0-2, cột 0-3).")
            
    except ValueError:
        print("Lỗi nhập liệu. Vui lòng nhập 2 số cách nhau bởi dấu cách.")

Bắt đầu trò chơi (Nhập tọa độ dạng: hang cot). Ví dụ: 0 0
[99, 99, 99, 99]
[99, 99, 99, 99]
[99, 99, 99, 99]
--------------------
Lỗi nhập liệu. Vui lòng nhập 2 số cách nhau bởi dấu cách.
Lỗi nhập liệu. Vui lòng nhập 2 số cách nhau bởi dấu cách.
Lỗi nhập liệu. Vui lòng nhập 2 số cách nhau bởi dấu cách.
Lỗi nhập liệu. Vui lòng nhập 2 số cách nhau bởi dấu cách.
Lỗi nhập liệu. Vui lòng nhập 2 số cách nhau bởi dấu cách.
Lỗi nhập liệu. Vui lòng nhập 2 số cách nhau bởi dấu cách.
Lỗi nhập liệu. Vui lòng nhập 2 số cách nhau bởi dấu cách.
Lỗi nhập liệu. Vui lòng nhập 2 số cách nhau bởi dấu cách.
Lỗi nhập liệu. Vui lòng nhập 2 số cách nhau bởi dấu cách.
Lỗi nhập liệu. Vui lòng nhập 2 số cách nhau bởi dấu cách.
Tọa độ ngoài phạm vi (hàng 0-2, cột 0-3).
[99, 99, 99, 99]
[99, 99, 99, 99]
[99, 'x', 99, 99]
--------------------
Tọa độ ngoài phạm vi (hàng 0-2, cột 0-3).
Tọa độ ngoài phạm vi (hàng 0-2, cột 0-3).
[99, 99, 99, 99]
[99, 99, 99, 99]
[99, 'x', 'o', 99]
--------------------
[99, 99, 99, 99]


2. cho y=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
 - lấy 4,5,6
 - lấy 2,5
 - lấy 3,4
 - lấy 9,6,3

In [2]:
y = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# 1. Lấy 4,5,6 
kq1 = y[1]
print("Lấy", kq1)

# 2. Lấy 2,5 
kq2 = [y[0][1], y[1][1]]
print("Lấy:", kq2)

# 3. Lấy 3,4 
kq3 = [y[0][2], y[1][0]]
print("Lấy:", kq3)

# 4. Lấy 9,6,3 
kq4 = [y[2][2], y[1][2], y[0][2]]
print("Lấy:", kq4)

Lấy [4, 5, 6]
Lấy: [2, 5]
Lấy: [3, 4]
Lấy: [9, 6, 3]


3. Cho x=[1,2,3,4,5,6,7,8,9,10]
- xuất các giá trị chẵn dùng `if`
- xuất các giá trị chẵn dùng `list comprehension`

In [4]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Cách 1: Dùng vòng lặp if
chan_if = []
for i in x:
    if i % 2 == 0:
        chan_if.append(i)
print("Số chẵn (dùng if):", chan_if)

# Cách 2: Dùng List Comprehension
chan_comp = [i for i in x if i % 2 == 0]
print("Số chẵn (dùng list comprehension):", chan_comp)

Số chẵn (dùng if): [2, 4, 6, 8, 10]
Số chẵn (dùng list comprehension): [2, 4, 6, 8, 10]


4. tạo 1 mảng numpy 150x5, giả sử mã này chứa 150 mẫu dữ liệu của sv bao gồm chiều cao, cân nặng, tuổi, lương, điểm TBM
- tách mảng dựa trên 4 cột đầu tiên thành 1 biến có tên là X, cột cuối cùng thành Y
- tách mảng X thành X_train và X_test, trong đó X_train chứa 70% dữ liệu, Y thành Y_train, Y_test, trong đó Y_train chứa 70% dữ liệu
- tạo 10 tập dữ liệu ko chồng chéo nhau

In [3]:
import numpy as np
import torch

# 1. Tạo dữ liệu giả lập
np.random.seed(42) # Để kết quả cố định mỗi lần chạy
data_np = np.random.rand(150, 5) * 100 # Nhân 100 để số liệu trông thực tế hơn chút

print(f"Kích thước dữ liệu gốc: {data_np.shape}")

# 2. Tách X (Features) và Y (Target)
X = data_np[:, :4] 
Y = data_np[:, 4]

print(f"Kích thước X: {X.shape}, Kích thước Y: {Y.shape}")

# 3. Tách Train (70%) và Test (30%)
split_idx = int(len(data_np) * 0.7) 

# Tách dữ liệu
X_train_np, X_test_np = X[:split_idx], X[split_idx:]
Y_train_np, Y_test_np = Y[:split_idx], Y[split_idx:]

print(f"X_train: {X_train_np.shape}, X_test: {X_test_np.shape}")

# CHUYỂN ĐỔI SANG PYTORCH 
X_train = torch.tensor(X_train_np, dtype=torch.float32)
X_test = torch.tensor(X_test_np, dtype=torch.float32)
Y_train = torch.tensor(Y_train_np, dtype=torch.float32)
Y_test = torch.tensor(Y_test_np, dtype=torch.float32)

print("\nĐã chuyển sang Pytorch Tensor:")
print(f"X_train tensor shape: {X_train.shape}")

# 4. Tạo 10 tập dữ liệu không chồng chéo nhau
cac_tap_con = np.array_split(data_np, 10)

print("\nKiểm tra các tập dữ liệu con (Subsets):")
for i, subset in enumerate(cac_tap_con):
    print(f"Tập {i+1} có kích thước: {subset.shape}")
    # Tập này hoàn toàn tách biệt, không chồng lấn lên tập khác

Kích thước dữ liệu gốc: (150, 5)
Kích thước X: (150, 4), Kích thước Y: (150,)
X_train: (105, 4), X_test: (45, 4)

Đã chuyển sang Pytorch Tensor:
X_train tensor shape: torch.Size([105, 4])

Kiểm tra các tập dữ liệu con (Subsets):
Tập 1 có kích thước: (15, 5)
Tập 2 có kích thước: (15, 5)
Tập 3 có kích thước: (15, 5)
Tập 4 có kích thước: (15, 5)
Tập 5 có kích thước: (15, 5)
Tập 6 có kích thước: (15, 5)
Tập 7 có kích thước: (15, 5)
Tập 8 có kích thước: (15, 5)
Tập 9 có kích thước: (15, 5)
Tập 10 có kích thước: (15, 5)
