# DEEP LEARNING
## *PYTORCH* basic

In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

torch.backends.mps.is_available()
torch.device("mps")


device(type='mps')

In [2]:
df = pd.read_csv("./Iris.csv")
df
df.shape

(150, 6)

In [3]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le = LabelEncoder()
X = df.drop(["Species"], axis=1).values
y = le.fit_transform(df["Species"].values)

#chia tập dữ liệu với test size 20%
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.LongTensor(y_train).reshape(-1, 1)
y_test = torch.LongTensor(y_test).reshape(-1, 1)


In [4]:
labels, counts = y_train.unique(return_counts=True)
print(labels, counts)

tensor([0, 1, 2]) tensor([40, 41, 39])


In [5]:
# tính đạo hàm bằng pytorch
# cho y = 2x^4 + x^3 + 3x^2 + 5 + 1
#tính y'
import torch

# Khởi tạo x (ví dụ x = 2.0)
x = torch.tensor(2.0, requires_grad=True)

# Định nghĩa hàm y
y = 2 * x**4 + x**3 + 3 * x**2 + 5*x + 1

# Tính đạo hàm dy/dx
y.backward()

print("y =", y.item())
print("y' =", x.grad.item())


y = 63.0
y' = 93.0


In [6]:
y = grad.fn
y.backward()

NameError: name 'grad' is not defined

In [7]:
import torch
torch.__version__

#chuyển đổi mảng numpy sang tensor pytorch

arr = np.array([1, 2, 3,4,5])
print(arr.dtype)
tensor = torch.from_numpy(arr)
print(tensor.type())
arr2 = np.arange(0,12).reshape(4,3)
print(arr2)
tensor2 = torch.from_numpy(arr2)
print(tensor2.type())

int64
torch.LongTensor
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
torch.LongTensor


In [9]:
x = torch.from_numpy(arr)
print(x)

arr[0] = 99
print(arr)

tensor([1, 2, 3, 4, 5])
[99  2  3  4  5]


In [20]:
arr3 = np.arange(0,5)
tensor = torch.tensor(arr3)
print(tensor)

tensor([0, 1, 2, 3, 4])


In [21]:
arr3[0] = 99
print(arr3)

[99  1  2  3  4]


# BTVN
# giai thich tai sao ko thay duoc 99 vao (lmao)

# BTWN 01

Cho y = 5x^5 + 6x^4 - 3x + 1

Cho biết độ dốc của đa thức trên ở điểm nào

In [1]:
import torch

# 1. Định nghĩa điểm cần tính đạo hàm (ví dụ x = 1.0)
# requires_grad=True là bắt buộc để PyTorch theo dõi các phép toán và tính đạo hàm
x = torch.tensor([1.0], requires_grad=True)

# 2. Định nghĩa hàm số y = 5x^5 + 6x^4 - 3x + 1
y = 5 * x**5 + 6 * x**4 - 3 * x + 1

# 3. Tính đạo hàm (Backpropagation)
y.backward()

# 4. Lấy giá trị độ dốc tại điểm x
slope = x.grad.item()

print(f"Độ dốc tại x = {x.item()} là: {slope}")

Độ dốc tại x = 1.0 là: 46.0


# BTVN 02

Tạo một tensor ban đầu có giá trị là 2

Định nghĩa hàm số và tính gradient

y = x^3 + 2x^2 + 5x + 1

Hãy tính dy/dx tại giá trị của x

Dùng phương pháp Gradient Descent với learning rate alpha = 0.1 để cập nhật giá trị x trong quá trình lặp

In [19]:
import torch

# Khởi tạo x
x = torch.tensor([2.0], requires_grad=True)
learning_rate = 0.01

print(f"Giá trị ban đầu x: {x.item()}")
print("-" * 30)

# Vòng lặp 50 lần
for i in range(50):
    # Tính toán hàm số và đạo hàm
    y = x**3 + 2*x**2 + 5*x + 1
    y.backward()
    
    # Lưu giá trị gradient hiện tại để in
    current_grad = x.grad.item()
    
    # Cập nhật x
    with torch.no_grad():
        x -= learning_rate * x.grad
        x.grad.zero_() # Reset gradient
        
    # In kết quả mỗi 3 vòng lặp để theo dõi
    if (i + 1) % 3 == 0 or i == 0:
        print(f"Vòng {i+1}: x = {x.item():.4f}, grad = {current_grad:.4f}")

print("-" * 30)
print(f"Giá trị cuối cùng của x: {x.item()}")

Giá trị ban đầu x: 2.0
------------------------------
Vòng 1: x = 1.7500, grad = 25.0000
Vòng 3: x = 1.3556, grad = 18.2500
Vòng 6: x = 0.9298, grad = 12.5641
Vòng 9: x = 0.6202, grad = 9.3857
Vòng 12: x = 0.3796, grad = 7.4339
Vòng 15: x = 0.1832, grad = 6.1590
Vòng 18: x = 0.0165, grad = 5.2921
Vòng 21: x = -0.1297, grad = 4.6892
Vòng 24: x = -0.2617, grad = 4.2680
Vòng 27: x = -0.3837, grad = 3.9793
Vòng 30: x = -0.4991, grad = 3.7933
Vòng 33: x = -0.6107, grad = 3.6925
Vòng 36: x = -0.7208, grad = 3.6676
Vòng 39: x = -0.8317, grad = 3.7157
Vòng 42: x = -0.9454, grad = 3.8400
Vòng 45: x = -1.0646, grad = 4.0500
Vòng 48: x = -1.1921, grad = 4.3632
------------------------------
Giá trị cuối cùng của x: -1.2835273742675781


## BTVN 03

Tạo một tập dữ liệu giả lập với:
	•	x là số giờ học (ngẫu nhiên từ 1 – 10)
	•	y là số điểm theo công thức:

y = 3x + 5 + noise

Trong đó noise là một giá trị ngẫu nhiên nhỏ

### Yêu cầu:
	1.	Khởi tạo tham số w và b ngẫu nhiên với requires_grad = True
	2.	Tính MSE
	3.	Tính Gradient
	4.	Cập nhật tham số w và b bằng Gradient Descent với learning rate alpha = 0.01
	5.	Lặp lại quá trình trên trong 100 vòng lặp để xem sự hội tụ của tham số

In [21]:
import torch

# Tạo tập dữ liệu giả lập 
torch.manual_seed(42) # Cố định seed để kết quả giống nhau mỗi lần chạy

# Tạo 20 mẫu dữ liệu
# X có giá trị ngẫu nhiên từ 1 đến 10
X = torch.rand(20) * 9 + 1  
noise = torch.randn(20) * 2  # Nhiễu ngẫu nhiên (standard normal distribution)

# Y theo công thức y = 3x + 5 + noise
Y_thuc_te = 3 * X + 5 + noise

print(f"Dữ liệu mẫu (5 điểm đầu):")
for i in range(5):
    print(f"  x: {X[i]:.2f} -> y: {Y_thuc_te[i]:.2f}")
print("-" * 50)

# Khởi tạo tham số w và b
w = torch.tensor([3.0], requires_grad=True) # Giả sử bắt đầu từ 0
b = torch.tensor([5.0], requires_grad=True)

learning_rate = 0.01

print(f"Tham số khởi tạo: w = {w.item():.2f}, b = {b.item():.2f}")
print("-" * 50)

# Vòng lặp huấn luyện (100 lần)
for epoch in range(100):
    
    # 1. Tính toán giá trị dự đoán (Forward pass)
    Y_du_doan = w * X + b
    
    # 2. Tính MSE 
    # Công thức: trung bình của (y_mũ - y_thực)^2
    loss = (Y_du_doan - Y_thuc_te).pow(2).mean()
    
    # 3. Tính Gradient (Backward pass)
    loss.backward()
    
    # 4. Cập nhật tham số
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad
        
        # Reset gradient về 0 sau khi cập nhật
        w.grad.zero_()
        b.grad.zero_()
        
    # In thông tin mỗi 10 vòng lặp
    if (epoch + 1) % 10 == 0:
        print(f"Vòng {epoch+1:3d}: Loss = {loss.item():.4f} | w = {w.item():.4f}, b = {b.item():.4f}")

print("-" * 50)
print("KẾT QUẢ CUỐI CÙNG:")
print(f"Mô hình học được:     w = {w.item():.4f}, b = {b.item():.4f}")

Dữ liệu mẫu (5 điểm đầu):
  x: 8.94 -> y: 30.31
  x: 9.24 -> y: 34.86
  x: 4.45 -> y: 19.94
  x: 9.63 -> y: 37.26
  x: 4.51 -> y: 18.61
--------------------------------------------------
Tham số khởi tạo: w = 3.00, b = 5.00
--------------------------------------------------
Vòng  10: Loss = 4.9043 | w = 3.0438, b = 5.0280
Vòng  20: Loss = 4.8997 | w = 3.0410, b = 5.0493
Vòng  30: Loss = 4.8952 | w = 3.0382, b = 5.0703
Vòng  40: Loss = 4.8909 | w = 3.0354, b = 5.0907
Vòng  50: Loss = 4.8868 | w = 3.0328, b = 5.1108
Vòng  60: Loss = 4.8829 | w = 3.0301, b = 5.1305
Vòng  70: Loss = 4.8791 | w = 3.0276, b = 5.1498
Vòng  80: Loss = 4.8754 | w = 3.0251, b = 5.1686
Vòng  90: Loss = 4.8719 | w = 3.0226, b = 5.1872
Vòng 100: Loss = 4.8686 | w = 3.0202, b = 5.2053
--------------------------------------------------
KẾT QUẢ CUỐI CÙNG:
Mô hình học được:     w = 3.0202, b = 5.2053


## BTVN 05
### Tạo tensor với
 - empty
 - zeros
 - ones
 - random
 - reshape với view và view as

In [18]:
import torch

print("TẠO TENSOR")

# 1. Empty: Tạo tensor chưa khởi tạo
# Lưu ý: Giá trị sẽ là "rác" (bất kỳ giá trị nào đang có trong ô nhớ đó), không phải luôn là 0.
t_empty = torch.empty(2, 3)
print(f"1. Empty (2x3):\n{t_empty}\n")

# 2. Zeros: Tạo tensor toàn số 0
t_zeros = torch.zeros(2, 3)
print(f"2. Zeros (2x3):\n{t_zeros}\n")

# 3. Ones: Tạo tensor toàn số 1
t_ones = torch.ones(2, 3)
print(f"3. Ones (2x3):\n{t_ones}\n")

# 4. Random: Tạo tensor ngẫu nhiên
# torch.rand tạo số ngẫu nhiên trong khoảng [0, 1) (phân phối đều)
t_rand = torch.rand(2, 3)
print(f"4. Random (2x3):\n{t_rand}\n")


print("RESHAPE VỚI VIEW")

# Tạo một tensor gốc có 12 phần tử (từ 0 đến 11)
t_goc = torch.arange(12) 
print(f"Tensor gốc (1D - 12 phần tử):\n{t_goc}\n")

# 5. Sử dụng .view()
# Biến đổi thành ma trận 3 hàng, 4 cột
# Lưu ý: Tích các chiều (3 * 4) phải bằng tổng số phần tử (12)
t_view = t_goc.view(3, 4)
print(f"5. View (3x4):\n{t_view}\n")

# Mẹo: Dùng -1 để PyTorch tự tính chiều còn lại
# Ví dụ: Muốn 2 hàng, còn bao nhiêu cột thì tự tính --> view(2, -1)
t_view_auto = t_goc.view(2, -1)
print(f"5. View tự động (2 hàng, tự tính cột):\n{t_view_auto}\n")


print("RESHAPE VỚI VIEW_AS")

# 6. Sử dụng .view_as()
# Giả sử ta có một tensor đích (target) nào đó
t_mau = torch.zeros(4, 3) # Tensor mẫu kích thước 4x3

# Ta muốn t_goc có hình dạng GIỐNG NHƯ t_mau
t_view_as = t_goc.view_as(t_mau)

print(f"Tensor mẫu shape: {t_mau.shape}")
print(f"6. View_as (biến t_goc theo t_mau):\n{t_view_as}")

TẠO TENSOR
1. Empty (2x3):
tensor([[0., 0., 0.],
        [0., 0., 0.]])

2. Zeros (2x3):
tensor([[0., 0., 0.],
        [0., 0., 0.]])

3. Ones (2x3):
tensor([[1., 1., 1.],
        [1., 1., 1.]])

4. Random (2x3):
tensor([[0.2018, 0.2018, 0.9497],
        [0.6666, 0.9811, 0.0874]])

RESHAPE VỚI VIEW
Tensor gốc (1D - 12 phần tử):
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

5. View (3x4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

5. View tự động (2 hàng, tự tính cột):
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

RESHAPE VỚI VIEW_AS
Tensor mẫu shape: torch.Size([4, 3])
6. View_as (biến t_goc theo t_mau):
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
